// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTL6bFUTEAk4fQIdt_0fVobNVEGVUc0cc',
    appId: '1:987154573700:web:4e0bb211cd5db5165895d1',
    messagingSenderId: '987154573700',
    projectId: 'guitarchords-c7e1e',
    authDomain: 'guitarchords-c7e1e.firebaseapp.com',
    storageBucket: 'guitarchords-c7e1e.appspot.com',
    measurementId: 'G-EVSSWQLEN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGtJkGSQBp4WSVyID-3dkCvSfWwh0-sM',
    appId: '1:987154573700:android:8fb2244d65598ae25895d1',
    messagingSenderId: '987154573700',
    projectId: 'guitarchords-c7e1e',
    storageBucket: 'guitarchords-c7e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVC6KkTbVoO6m63KJ-hDJZA1CGTAHpj2Q',
    appId: '1:987154573700:ios:0ae9bd18c0a40c565895d1',
    messagingSenderId: '987154573700',
    projectId: 'guitarchords-c7e1e',
    storageBucket: 'guitarchords-c7e1e.appspot.com',
    iosClientId: '987154573700-bb0kldda72l3cmb6n677pf132k1ufpee.apps.googleusercontent.com',
    iosBundleId: 'com.example.guitarchords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVC6KkTbVoO6m63KJ-hDJZA1CGTAHpj2Q',
    appId: '1:987154573700:ios:0ae9bd18c0a40c565895d1',
    messagingSenderId: '987154573700',
    projectId: 'guitarchords-c7e1e',
    storageBucket: 'guitarchords-c7e1e.appspot.com',
    iosClientId: '987154573700-bb0kldda72l3cmb6n677pf132k1ufpee.apps.googleusercontent.com',
    iosBundleId: 'com.example.guitarchords',
  );
}
